config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  resources :users, only: [:index, :show, :edit, :update]
  resources :posts, only: [:new, :create, :index, :show, :destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  
  # userモデルとN:1の関係
  belongs_to :user
  
  #バリデーション
  
  # 値の入力は必須であり、数値かつ０以上の正の整数でなければならない
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }
  
  # カテゴリーの選択は必須
  validates :category, presence: true
  
  # 商品名の入力は必須であり、最大５０文字
  validates :product, presence: true, length: { maximum: 50 }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attachment :profile_image
  
  # postモデルと1:Nの関係
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # ユーザーが認証されているか確認する（topページは例外）
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # 新規記録作成のviewページ
  def new
    @post = Post.new
  end

# 新規記録作成
  def create
    post = Post.new(post_params)
    post.user_id = current_user.id
    post.purchase_status = false
    if post.save
      redirect_to posts_path(current_user)
    else
      render :new
    end
  end

# 記録一覧ページ
  def index

    # 日付に関するデータを収集
    @month = params[:month]
    if @month.nil?
    @month = Date.current
    else
    @month = @month.slice(0..9)
    end

    # 1ヶ月ごとのデータを収集し、Viewに表示する
    @total_posts = Post.where(user_id: current_user.id).order("created_at DESC")
    # 月ごとの投稿をまとめたハッシュであり、キーは月の最初の日時（YYYY-MM-01 00:00:00）
    @total_posts_month = @total_posts.group_by { |post| post.created_at.beginning_of_month }

    #表示する月の選択
    @selected_month = Date.parse(params[:month]) rescue Date.today.at_beginning_of_month

    #1ヶ月間に買ったものの一覧（purchase_statusがtrueのデータ）
    @posts_buy = Post.where(purchase_status: true).where(user_id: current_user.id).where(created_at: @month.in_time_zone.all_month).order("created_at DESC")

    #1ヶ月に我慢したものの一覧（purchase_statusがfalseのデータ）
    @posts_unbuy = Post.where(purchase_status: false).where(user_id: current_user.id).where(created_at: @month.in_time_zone.all_month).order("created_at DESC")

  end

  #投稿データの詳細
  def show
    @post = Post.find(params[:id])
  end

  #「買った」ボタンを押した際に「買ったもの」に振り分けられる
  def update
    post = Post.find(params[:id])

    #「purchase_status」がfalseからtrueに変更する
    post.purchase_status = true

    post.save
    redirect_to posts_path

  end

  # 投稿データの削除
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:price, :category, :product, :comment)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #ユーザー一覧ページ
  def index
    #ページングを使用し、10人ずつ表示される
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])

    #月の最初と終わりの定義
    @start_date = Date.current.beginning_of_month
    @end_date = @start_date.end_of_month

    #1ヶ月の間に投稿された「買ったもの」と「我慢したもの」を収集
    @posts_buy = Post.where(purchase_status: true).where(user_id: current_user.id).order("created_at DESC").where(created_at: @start_date..@end_date)
    @posts_unbuy = Post.where(purchase_status: false).where(user_id: current_user.id).order("created_at DESC").where(created_at: @start_date..@end_date)

    #収集されたそれぞれのデータの合計金額
    @total_buy = @posts_buy.sum(:price)
    @total_unbuy = @posts_unbuy.sum(:price)

    #そのユーザーの持つ過去の我慢額の総額の表示
    @user_unbuy = Post.where(purchase_status: false).where(user_id: current_user.id)
    @all_unbuy = @user_unbuy.sum(:price)

    #ユーザーが目標金額を設定していた場合、達成率を表示
    if @user.goal_money.present?
      
      @goal_money = @user.goal_money
      # 小数第二位まで計算(to_fメソッドで数値を浮動小数点数にし、roundメソッドで小数第二位まで計算している)
      @completion_rate = (@total_unbuy.to_f / @user.goal_money).round(2)

    #設定していない場合、０を表示
    else
      @goal_money = 0
      @completion_rate = 0

    end

    #簡易的なユーザー一覧の表示
    @users = User.page(params[:page]).reverse_order
    @users.each do |user|
      #それぞれのユーザーの過去の我慢額を表示
      posts_unbuy = user.posts.where(purchase_status: false)
      total_unbuy = posts_unbuy.sum(:price)
      user.total_unbuy = total_unbuy
    end

  end

  #ユーザー情報の編集ページ
  def edit
    @user = User.find(params[:id])
  end

  #ユーザー情報の更新
  def update
    user = User. find(params[:id])
    user .update(user_params)
    redirect_to user_path(current_user)
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :goal_comment, :goal_money)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<!--ログイン前でも閲覧可能なトップページ-->
<div class="container text-center">

  <h2 class="top-title"><strong>Welcome Tamemol!!</strong></h2>

  <h4 class="top-text">
    Tamemolは、毎日のちょっとした無駄遣いをなくすことをサポートするWebアプリケーション！<br>
    カンタンな機能で無駄遣いを把握し、節約につなげることができます。<br>
    また、他のユーザーと一緒に無駄遣いを無くすことで、節約意欲が高まることも。<br>
    Tamemolを使って、あなたも無駄遣いを減らし、賢くお金を使うライフスタイルを手に入れよう！<br>
  </h4>

  <div class="btn-wrapper col-4 mx-auto">

    <!--ユーザーがサインインしていなければ表示されるボタン-->
    <% unless user_signed_in? %>
    <div class="row">
      <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
    </div>
    <div class="row">
      <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
    </div>
    <% end %>

  </div>

</div>

app/views/layouts/_footer.html.erb
<!--ページのフッター部のレイアウト-->
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!--ページのヘッター部のレイアウト-->
<nav class="navbar navbar-expand-lg navbar-light navbar-dark-custom">
  <div class="navbar-brand">Tamemol</div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <!--ユーザーがログインしている場合-->
      <% if user_signed_in? %>
      <li class="nav-item">
        <a class="nav-link text-right" href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-right" href="/users/<%= current_user.id %>">My page</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-right" href="/users">Users</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-right" href="/posts">List</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-right" rel="nofollow" data-method="delete" href="/users/sign_out">Log out</a>
      </li>

      <!--ユーザーがログインしていない場合-->
      <% else %>
      <li class="nav-item">
        <a class="nav-link text-right" href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-right" href="/users/sign_up">Sign up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-right" href="/users/sign_in">Log in</a>
      </li>
      <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tamemol</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!--レスポンシブ対応-->
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!--fontawesome使用-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-ZCpNsIE9eBpRnEJpOVYvPuaFfQP0wL1eMvuksKfQskZI+Pn5UoJI7W+L6YzV7l+" crossorigin="anonymous">

  </head>

  <body>
    <div class="contents">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container">
  <!--表示する月の選択-->
  <div class="month-date">
    <!--@total_posts_monthの.keysメソッドでハッシュのキー（月の最初の日時）を返し、.mapメソッドで配列の要素に指定された処理を行い、新しい配列を生成する-->
    <%= form_tag(posts_path, method: "get") do %>
      <%= select_tag "month", options_for_select(@total_posts_month.keys.map{ |date| [date.strftime('%Y年%m月'), date] }, selected: params[:month]), include_blank: false %>
      <%= submit_tag "月を選択" %>
    <% end %>
    <h1 class="month-view"><%= @selected_month.strftime('%Y年%m月') %>のリスト</h1>
  </div>
  
  <!--我慢しているものリスト-->
  <h3 class="posts-title">我慢中</h3>
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th colspan="2">商品名</th>
        <th colspan="2">金額</th>
        <th colspan="2">カテゴリー</th>
        <th colspan="2"></th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @posts_unbuy.each do |post| %>
        <tr>
          <th colspan="2">
            <%= link_to post_path(post.id) do %>
              <%= post.product %>
            <% end %>
          </th>
          <th colspan="2">
            <%= post.price %>
          </th>
          <th colspan="2">
            <%= post.category %>
          </th>
          <!--買ったボタンを押すことで「purchase_status」がtrueとなり買ったものに振り分けられる-->
          <th colspan="2">
            <% if post.purchase_status == false %>
              <%= link_to "買った", post_path(post), class: "btn btn-dark", method: :patch %>
            <% end %>
          </th>
          <th colspan="2">
            <%= link_to "削除", post_path(post), class: "btn btn-dark", method: :delete %>
          </th>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <!--買ったものリスト-->
  <h3 class="posts-title">買ったもの</h3>
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th colspan="2">商品名</th>
        <th colspan="2">金額</th>
        <th colspan="2">カテゴリー</th>
        <th colspan="2"></th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @posts_buy.each do |post| %>
        <tr>
          <th colspan="2">
            <%= link_to post_path(post.id) do %>
              <%= post.product %>
            <% end %>
          </th>
          <th colspan="2">
            <%= post.price %>
          </th>
          <th colspan="2">
            <%= post.category %>
          </th>
          <th colspan="2"></th>
          <th colspan="2">
            <%= link_to "削除", post_path(post), class: "btn btn-dark", method: :delete %>
          </th>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <!--それぞれのページへ遷移する-->
  <div class="text-center">
    <%= link_to "記録する", new_post_path, class: "btn btn-dark" %>
    <%= link_to "My pageへ", user_path(current_user), class: "btn btn-dark" %>
  </div>
  
</div>

app/views/posts/new.html.erb
<!--新規記録の作成ページ-->
<div class="container">
  <h2 class="text-center mb-4">新しい記録</h2>
  <%= form_with model:@post, local: true do |f| %>
    <div class="form-group text-center">
      <h4>商品名</h4>
      <%= f.text_field :product, class: 'form-control w-25 mx-auto' %>
    </div>

    <div class="form-group text-center">
      <h4>カテゴリー</h4>
      <%= f.select :category, options_for_select(['食品', '日用品', '交通費', '趣味', 'その他'])%>
    </div>

    <div class="form-group text-center">
      <h4>金額(半角数字のみ入力)</h4>
      <%= f.text_field :price, class: 'form-control w-25 mx-auto' %>
    </div>

    <div class="text-center">
      <%= f.submit '保存', class: 'btn btn-primary w-25 mx-auto mt-4' %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<!--投稿された商品の詳細ページ-->

  <div class="post-details">
    <h1 class="show-top">商品詳細</h1>
    <div class="post-details__item">
      <h4 class="post-title">商品名</h4>
      <p class="post-date"><%= @post.product %></p>
    </div>
    <div class="post-details__item">
      <h4 class="post-title">カテゴリー</h4>
      <p class="post-date"><%= @post.category %></p>
    </div>
    <div class="post-details__item">
      <h4 class="post-title">金額</h4>
      <p class="post-date">¥<%= @post.price %></p>
    </div>
    <div class="post-details__buttons">
      <%= link_to "記録画面へ", new_post_path, class: "btn btn-dark" %>
      <%= link_to "My pageへ", user_path(current_user), class: "btn btn-dark" %>
    </div>
  </div>

app/views/users/edit.html.erb
<!--ユーザー情報編集ページ-->
<div class="container">
  <h2 class="text-center mb-4">プロフィール編集</h2>
  <%= form_with model:@user, local: true do |f| %>
    <div class="form-group text-center">
      <h4>Name</h4>
      <%= f.text_field :name, class: 'form-control w-25 mx-auto' %>
    </div>

    <div class="form-group text-center">
      <h4>プロフィール画像</h4>
      <%= f.attachment_field :profile_image %>
    </div>

    <div class="form-group text-center">
      <h4>目標</h4>
      <%= f.text_area :goal_comment, class: 'form-control w-50 mx-auto' %>
    </div>

    <div class="form-group text-center">
      <h4>目標金額</h4>
      <%= f.text_field :goal_money, class: 'form-control w-25 mx-auto' %>
    </div>

    <div class="text-center">
      <%= f.submit '更新', class: 'btn btn-primary w-25 mx-auto mt-4' %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<!--ユーザー一覧ページ-->
<div class="index-main">
  <h2 class="text-center">ユーザー一覧</h2>
  <div class="card-container">
    <% @users.each do |user| %>
      <div class="card bg-transparent border" style="width: 18rem;">
        <div class="card-body">
          <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpg', fallback: "default-image.jpg", class: "rounded-image"%>
          <h5 class="card-title"><%= user.name %></h5>
          <p class="card-text">目標：<%= user.goal_comment %></p>
          <p class="card-text">目標金額: ¥<%= user.goal_money %></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex justify-content-center">
    <%= paginate @users %>
  </div>
  <div class="center">
    <%= link_to "My pageへ", user_path(current_user.id), class: "btn btn-dark btn-lg btn-tall btn-center" %>
  </div>
</div>

app/views/users/show.html.erb
<!--ユーザー詳細ページ-->
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="row">

        <!--ユーザーデータ表示-->
        <div class="col-md-9 border">
          <div class="wrapper">
            <div class="user_info">
              <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpg', fallback: "default-image.jpg", class: "rounded-image"%>
              <strong style="font-size: 24px;"><%= @user.name %></strong>
              <%= link_to "編集", edit_user_path(@user), class: "btn btn-dark" %>
            </div>
            <div class="info_wrapper">
              <div class="money_info">
                <p class="money_text">
                  <i class="fas fa-fire" style="color: #ff6b6b">我慢目標</i>
                  <span><strong>¥<%= @user.goal_money %></strong></span>
                </p>
                <p class="money_text">
                  <i class="fas fa-thumbs-up" style="color: #fcdd57">我慢した</i>
                  <span><strong>¥<%= @total_unbuy %></strong></span>
                </p>
                <p class="money_text">
                  <i class="fas fa-yen-sign" style="color: #80d4ff">買った</i>
                  <span><strong>¥<%= @total_buy %></strong></span>
                </p>
              </div>
              <p class="goal_text">目標:<%= @user.goal_comment %></p>
            </div>
          </div>
        </div>

        <!--ユーザー一覧部分-->
        <div class="offset-md-1 col-md-2 text-center border">
          <%= link_to users_path do %>
            <p class="all_users mt-3"><strong>みんなの我慢額</strong></p>
          <% end %>
          <% @users.each do |user| %>
            <div class="d-flex align-items-center" style="margin-bottom: 10px;">
              <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpg', fallback: "default-image.jpg", class: "rounded-image", style: "margin-right: 20px" %>
              ¥ <%= user.total_unbuy %>
            </div>
          <% end %>
          <div class="d-flex align-items-center">
            <%= paginate @users %>
          </div>
        </div>

      </div>
    </div>

    <div class="col-md-12">
      <div class="row">

        <!--ユーザーの今月の我慢目標達成率-->
        <div class="col-md-4 text-center goal-rate small-text border">
          <p class="goal-rate-text">目標達成率</p>
          <!--目標達成率が２０％以下の時は赤、50％以下の時は黄色、80％以下の時は緑、それ以上は青になる-->
          <p class="my-money" style="color:
            <% if @completion_rate <= 0.2 %>
              #ff6b6b;
            <% elsif @completion_rate <= 0.5 %>
              #fcdd57;
            <% elsif @completion_rate <= 0.8 %>
              #43FF6B;
            <% else %>
              #80d4ff;
            <% end %>"
          >

            <strong><%= @completion_rate * 100 %>%</strong>
          </p>

          <% if @user.goal_money.present? && @user.goal_money > 0 %>
            <p class="goal-rate-text">目標達成まであと...<strong>¥<%= @user.goal_money - @total_unbuy %></strong></p>
          <% end %>

        </div>

        <!--過去の我慢金額の合計-->
        <div class="offset-md-1 col-md-4 text-center total-unbuy small-text border">
          <p class="under-text">今までの我慢合計</p>
          <p class="my-money"><strong>¥<%= @all_unbuy %></strong></p>
        </div>

        <!--ページ遷移ボタン-->
        <div class="offset-md-1 col-md-2 d-flex align-items-center justify-content-center">
          <div class="d-flex flex-column justify-content-between">
            <%= link_to "記録する", new_post_path, class: "btn btn-dark btn-block btn-tall" %>
            <%= link_to "記録一覧", posts_path, class: "btn btn-dark btn-block btn-tall" %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>